name: Update contests.json daily

on:
  schedule:
    - cron: "30 18 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-contests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Fetch latest contests
        run: |
          curl -s https://competeapi.vercel.app/contests/upcoming -o src/json/contests.json

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add src/json/contests.json
          git commit -m "Update contests.json automatically" || echo "No changes to commit"
          git push origin main
